name: Continuous Integration

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Execute CI script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and run Parsec with the Mbed Crypto provider
        run: |
          git clone https://github.com/parallaxsecond/parsec.git
          cd parsec
          cargo build --features "mbed-crypto-provider"
          ./target/debug/parsec -c ../tests/test_config.toml &
      - name: Execute CI script
        run: ./tests/ci.sh

  links:
    name: Check links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Link Checker
      uses: peter-evans/link-checker@v1
      with:
        args: -v -r *.md
    - name: Fail if there were link errors
      run: exit ${{ steps.lc.outputs.exit_code }}
